### ISSUE TITLE
AttributeError: module 'serial' has no attribute 'Serial'

### ISSUE THREAD

**Issue by patrickpoirier51** [Civlo85/gsmHat#3]
Hello,

Just loaded on RPI3 with fresh raspios-buster image

python3 test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    gsm = GSMHat('/dev/ttyS0', 115200)
  File "/home/pi/.local/lib/python3.7/site-packages/gsmHat/gsmHat.py", line 74, in __init__
    self.__connect()
  File "/home/pi/.local/lib/python3.7/site-packages/gsmHat/gsmHat.py", line 78, in __connect
    self.__ser = serial.Serial(self.__port, self.__baudrate)
AttributeError: module 'serial' has no attribute 'Serial'

tried
pip3 instll pyserial

same error

**Comment by HubertFeldmann** [comment]
do this:
pip uninstall serial
pip install pyserial
